#!/bin/sh

DIR="/opt"

if [ "$(id -u)" != "0" ]; then
        echo "This script must be run as root!"
        exit 1
fi

wget -q --spider http://www.google.com
if [ "$?" != 0 ]; then
        echo "This script must be run with internet connection!"
        exit 1
fi

cd $DIR
git clone git://github.com/beagleboard/am335x_pru_package.git
export CROSS_COMPILE=
cd $DIR"/am335x_pru_package/pru_sw/app_loader/interface"
make
cd "../../utils/pasm_source/"
source ./linuxbuild
cd ..
mv pasm pasm_2
