#!/bin/sh

DIR="/opt"

# Verify requisites

if [ "$(id -u)" != "0" ]; then
        echo "This script must be run as root!"
        exit 1
fi

wget -q --spider http://www.google.com
if [ "$?" != 0 ]; then
        echo "This script must be run with internet connection!"
        exit 1
fi

# Clone and configure the am335x_pru_package

cd $DIR
git clone git://github.com/beagleboard/am335x_pru_package.git
export CROSS_COMPILE=
cd $DIR"/am335x_pru_package/pru_sw/app_loader/interface"
make
cd "../../utils/pasm_source/"
cd $DIR"/am335x_pru_package/pru_sw/app_loader/interface"
cd "../../utils/pasm_source/"
. ./linuxbuild
cd ..
#mv pasm pasm_2 # necessary in old version

# Edit the device tree to enable the PRU

cd /boot/uboot/dtbs/
cp am335x-boneblack.dtb am335x-boneblack.dtb_orig
dtc -I dtb -O dts am335x-boneblack.dtb > am335x-boneblack.dts

awk '
        BEGIN {
                a = 5
        }
        /reg = <0x4a300000 0x80000>;/ {
                a = 0
        }
        {
                a = a + 1
                if(a == 4) {
                        $0 = "			status = \"okay\";"
                        print $0
                }
                else {
                        print $0
                }
        }
        END {
        }
' am335x-boneblack.dts > tmp && mv tmp am335x-boneblack.dts

dtc -I dts -O dtb am335x-boneblack.dts > am335x-boneblack.dtb

echo "am335x_pru_package install successful."
echo "You must reboot for the changes take effect!"
