#!/bin/sh

DIR="/opt/am335x_pru_package"

if [ "$(id -u)" != "0" ]; then
        echo "This script must be run as root!"
        exit 1
fi

if [ -d $DIR ]; then
    rm -r $DIR
    echo "am335x_pru_package directory removed"
fi

echo "am335x_pru_package uninstall successful."
